### ISSUE TITLE
Support for Events?

### ISSUE THREAD

**Issue by gourgouris** [Workiva/opentelemetry-dart#116]
**Is your feature request related to a problem? Please describe.**
The library does not support Events (throws [UnimplementedError](https://github.com/Workiva/opentelemetry-dart/blob/815985946cd7c2d1be3423818d3d988a12183173/lib/src/sdk/trace/span.dart#L169))

**Describe the solution you'd like**
I'd like to use events to track pageviews and non-fatal exceptions/traces.
For a Flutter application, tracking these 2 I think makes sense in order to investigate potential issues. It is not enough to see an HTTP call to the server, without knowing the page flow of the user or if there were any exceptions on the client side.
Thats what Open Telemetry is for, at least in my mind: to give you a clear view of what is going on inside the components of your production.

**Describe alternatives you've considered**
I have considered "recordException" or attributes, but this will only record the latest value of each key. This is not helpful as there may be multiple "pages" or "traces" in a single span.
I have also considered new spans for each trace, but that is suboptimal, given that most SaaS collectors charge per span.
Unfortunatelly this is what I have to use for now.

**Additional context**
Awsome effort, looking forward to events and nullability support, thank you so much!
PS: I am using the opentelemetry_sls: ^0.15.1 package, because your package does not support Dart 3.

**Comment by StephenWithPH** [comment]
@michaelyeager-wf ...

First, many thanks to Workiva for maintaining and open-sourcing this. It was quite easy to get a sample Flutter app wired with telemetry. Great work!

---

I see you added:
https://github.com/Workiva/opentelemetry-dart/blob/322f988a3bc43a2ffe8dff1973e8983c61dedcf1/lib/src/sdk/trace/span.dart#L155-L160

**I would like to know if you are open to a PR to implement this.**

I roughed in a prototype locally and was able to get it successfully recording events. I'm using a local Jaeger instance for proof-of-life:

![Screenshot 2023-11-14 at 1 51 23 PM](https://github.com/Workiva/opentelemetry-dart/assets/2990492/64f15725-622a-4735-b593-b19d59edbfde)


From a high-level, I expect the PR would look something like:
- adjust `addEvent` to make `timestamp` a named, optional (aligns with [the spec](https://opentelemetry.io/docs/specs/otel/trace/api/#add-events)) whose default value is `_timeProvider.now`:
  https://github.com/Workiva/opentelemetry-dart/blob/322f988a3bc43a2ffe8dff1973e8983c61dedcf1/lib/src/api/trace/span.dart#L63
- create `Iterable<pb_trace.Span_Event> _spanEventsToPb(List<SpanEvent> events)` in [lib/src/sdk/trace/exporters/collector_exporter.dart](./lib/src/sdk/trace/exporters/collector_exporter.dart)
  - add a call to that to populate `pb_trace.Span`'s `events` in:
    https://github.com/Workiva/opentelemetry-dart/blob/322f988a3bc43a2ffe8dff1973e8983c61dedcf1/lib/src/sdk/trace/exporters/collector_exporter.dart#L136-L150
- create an (sdk rather than api) `SpanEvent` along the lines of:
  ```dart
  class SpanEvent {
    const SpanEvent(this.name, this.eventTime, this.attributes);


    final Int64 eventTime;
    final String name;
    final List<api.Attribute> attributes;
  }
  ```
  - note that I'm consciously avoiding any of the _Log_-specific semantics around events; the above is narrowly an Event in the context of a Trace
  - I'm also avoiding any potential work related to treating a _Trace_'s Exceptions as a form of an Event, as alluded to:
    https://github.com/Workiva/opentelemetry-dart/blob/322f988a3bc43a2ffe8dff1973e8983c61dedcf1/lib/src/sdk/trace/span.dart#L141

---

Please consider all of the above. If you would entertain a PR along these lines, please let me know.
